version: '2'

services:
  kapacitor:
    image: kapacitor:1.2-alpine
    container_name: kapacitor
    network_mode: "host"
    depends_on:
      - telegraf

  telegraf:
    image: telegraf:1.2-alpine
    container_name: telegraf
    depends_on:
      - influx
    network_mode: "host"
    volumes: 
      - "${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"

  influx:
    image: influxdb:1.2-alpine
    container_name: influx
    network_mode: "host"
    volumes: 
      - "${PWD}/influxdb.conf:/etc/influxdb/influxdb.conf:ro"

  chronograf:
    image: chronograf
    container_name: chronograf
    depends_on:
      - influx    
    network_mode: "host"
    volumes: 
      - "${PWD}/chronograf.conf:/etc/chronograf/chronograf.conf:ro"


  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   depends_on:
  #   - influx
  #   links:
  #     - influx
  #   ports:
  #     - "3000:3000"
